#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
LC_ALL=C
if [[ "$EUID" != "0" ]]; then
	echo -e "\e[00;31mERROR: DEBES SER ROOT\e[00m"
	exit 1
fi
case "$1" in
	server)
		apt -q update
		apt -y install nfs-kernel-server
		mkdir /swap
		dd if=/dev/zero of=/swap/swapfile bs=1024 count=1048576
		echo "/swap 192.168.1.1(rw,insecure,sync)" >> /etc/exports
		chmod -v 777 /swap/swapfile
		exportfs -r
		echo -e "\e[00;1;92mFinished...\e[00m"
		;;

	client)
		apt -q update
		apt -y install nfs-common
		mkdir /swap
		echo "192.168.1.1:/swap /swap nfs user,exec" >> /etc/fstab
		mount /swap
		losetup /dev/loop0 /swap/swapfile
		mkswap /dev/loop0
		swapon /dev/loop0
		echo -e "\e[00;1;92mFinished...\e[00m"
		;;

	*)
		echo "uso: $(basename $0) {server|client}"
		;;

esac

exit 0
